/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.views;

import com.mycompany.ilib.DAOUsersImpl;
import com.mycompany.ilib.Dashboard;
import com.mycompany.interfaces.DAOUsers;
import java.awt.Color;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author William May
 */
public class FormLogin extends javax.swing.JFrame {

    /**
     * Creates new form FormLogin
     */
    public FormLogin() {
        initComponents();
        this.setLocationRelativeTo(this);
        jTextUser.setForeground(Color.GRAY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        jTextUser = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblUser = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblPassword = new javax.swing.JLabel();
        jTextPass = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnLog = new javax.swing.JButton();
        btnGetInto = new javax.swing.JButton();
        lblShow = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(112, 145, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/userInicio.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 59, -1, -1));

        lblTitle.setBackground(new java.awt.Color(255, 255, 255));
        lblTitle.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Acceso");
        jPanel1.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 11, -1, -1));

        jTextUser.setBackground(new java.awt.Color(112, 145, 255));
        jTextUser.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jTextUser.setForeground(new java.awt.Color(255, 255, 255));
        jTextUser.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextUser.setText("INGRESE SU CORREO");
        jTextUser.setBorder(null);
        jTextUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextUserMousePressed(evt);
            }
        });
        jTextUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextUserActionPerformed(evt);
            }
        });
        jPanel1.add(jTextUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 270, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 265, 235, 35));

        lblUser.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUser.setText("Usuario:");
        jPanel1.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 213, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 358, 235, 41));

        lblPassword.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("Contraseña:");
        jPanel1.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 301, -1, -1));

        jTextPass.setBackground(new java.awt.Color(112, 145, 255));
        jTextPass.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jTextPass.setForeground(new java.awt.Color(255, 255, 255));
        jTextPass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextPass.setText("**************");
        jTextPass.setBorder(null);
        jTextPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextPassMousePressed(evt);
            }
        });
        jTextPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextPassKeyTyped(evt);
            }
        });
        jPanel1.add(jTextPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 240, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/userLabel.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 352, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/key.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        btnLog.setBackground(new java.awt.Color(81, 84, 255));
        btnLog.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        btnLog.setForeground(new java.awt.Color(255, 255, 255));
        btnLog.setText("Iniciar sesión");
        btnLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogActionPerformed(evt);
            }
        });
        jPanel1.add(btnLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 405, -1, 42));

        btnGetInto.setBackground(new java.awt.Color(112, 145, 255));
        btnGetInto.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        btnGetInto.setForeground(new java.awt.Color(255, 255, 255));
        btnGetInto.setText("Registrarse");
        btnGetInto.setBorder(null);
        btnGetInto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetIntoActionPerformed(evt);
            }
        });
        jPanel1.add(btnGetInto, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 453, 125, 42));

        lblShow.setBackground(new java.awt.Color(255, 255, 255));
        lblShow.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        lblShow.setForeground(new java.awt.Color(255, 255, 255));
        lblShow.setText("Mostrar");
        lblShow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblShowMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblShowMouseExited(evt);
            }
        });
        jPanel1.add(lblShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 70, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextUserActionPerformed

    private void btnLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogActionPerformed
        // TODO add your handling code here:
        //  consultas con = new consultas();
        // con.consultarUsuario(jTextUser.getText(), jTextPass.getText());

        String correo = jTextUser.getText(), pass = new String(jTextPass.getPassword());
        if (correo.isEmpty() || pass.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe llenar todos los campos. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        DAOUsers dao = new DAOUsersImpl();

        try {
            List<com.mycompany.models.Users> list = dao.listarEmail(correo);
            com.mycompany.models.Users user = null;
            System.out.println(list.size());
            for (int i = 0; i < list.size(); i++) {
                com.mycompany.models.Users user1 = list.get(i);

                String password = user1.getPassword();

                if (password.equals(pass)) {

                    user = list.get(i);
                    break;
                }
            }
            if (user == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "Usuario no encontrado\n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
            javax.swing.JOptionPane.showMessageDialog(this, "Bienvenido " + user.getName() + " " + user.getLast_name_p() + "\n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            this.setVisible(false);
            if (user.getRole().equals("work")) {
                new Dashboard().setVisible(true);
                
            } else {
                new Admins().setVisible(true);
            }

        } catch (NullPointerException ex) {
            ex.printStackTrace();
        } catch (Exception ex) {
            Logger.getLogger(FormLogin.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnLogActionPerformed

    private void btnGetIntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetIntoActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        FormRegistro form = new FormRegistro();
        form.setVisible(true);
    }//GEN-LAST:event_btnGetIntoActionPerformed

    private void lblShowMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblShowMouseEntered
        // TODO add your handling code here:

        jTextPass.setEchoChar((char) 0);
    }//GEN-LAST:event_lblShowMouseEntered

    private void lblShowMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblShowMouseExited
        // TODO add your handling code here:
        jTextPass.setEchoChar('*');
    }//GEN-LAST:event_lblShowMouseExited

    private void jTextUserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextUserMousePressed
        // TODO add your handling code here:
        if (jTextUser.getText().equals("Ingrese su correo".toUpperCase())) {
            jTextUser.setText("");
            jTextUser.setForeground(Color.BLACK);
        }
        if (String.valueOf(jTextPass.getPassword()).isEmpty()) {
            jTextPass.setText("**************");
            jTextPass.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_jTextUserMousePressed

    private void jTextPassMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextPassMousePressed
        // TODO add your handling code here:
        if (String.valueOf(jTextPass.getPassword()).equals("**************")) {
            jTextPass.setText("");
            jTextPass.setForeground(Color.BLACK);
        }
        if (jTextUser.getText().isEmpty()) {
            jTextUser.setText("Ingrese su correo".toUpperCase());
        }
        jTextUser.setForeground(Color.GRAY);

    }//GEN-LAST:event_jTextPassMousePressed

    private void jTextPassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextPassKeyTyped
        // TODO add your handling code here:
        
        if (jTextPass.getPassword().length == 8) {
            evt.consume();  // Ignorar la entrada de caracteres no deseados
        }
    }//GEN-LAST:event_jTextPassKeyTyped

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGetInto;
    private javax.swing.JButton btnLog;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPasswordField jTextPass;
    private javax.swing.JTextField jTextUser;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblShow;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUser;
    // End of variables declaration//GEN-END:variables
}
