/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.views;

import com.mycompany.ilib.DAOUsersImpl;
import com.mycompany.interfaces.DAOUsers;
import static com.mycompany.views.UpUsers.codigo;
import java.awt.Dimension;
import java.io.IOException;
import java.io.InputStream;
import java.util.Calendar;
import java.util.Properties;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.activation.DataHandler;
import javax.activation.DataSource;
import javax.mail.AuthenticationFailedException;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Multipart;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.MimeMultipart;
import javax.mail.util.ByteArrayDataSource;
import javax.swing.JOptionPane;

/**
 *
 * @author William May
 */
public class FormRegistro extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;
    private String email;
    private String subject;
    private String message;
    static String codigo = "";

    /**
     * Creates new form FormRegistro
     */
    public FormRegistro() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jTextClave = new javax.swing.JTextField();
        jbtnGuardar = new javax.swing.JButton();
        jbtnGuardar1 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jTextNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        txtApellidoMa = new javax.swing.JTextField();
        txtApellidoPa = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(112, 145, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Regístrese");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 19, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Clave (8 Carácteres):");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Apellido Materno");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 235, 18));

        jTextClave.setBackground(new java.awt.Color(112, 145, 255));
        jTextClave.setForeground(new java.awt.Color(255, 255, 255));
        jTextClave.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextClave.setBorder(null);
        jTextClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextClaveActionPerformed(evt);
            }
        });
        jTextClave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextClaveKeyTyped(evt);
            }
        });
        jPanel1.add(jTextClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 235, -1));

        jbtnGuardar.setBackground(new java.awt.Color(81, 84, 255));
        jbtnGuardar.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jbtnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        jbtnGuardar.setText("Guardar");
        jbtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, -1, -1));

        jbtnGuardar1.setBackground(new java.awt.Color(81, 84, 255));
        jbtnGuardar1.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jbtnGuardar1.setForeground(new java.awt.Color(255, 255, 255));
        jbtnGuardar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/previous.png"))); // NOI18N
        jbtnGuardar1.setText("Volver ");
        jbtnGuardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGuardar1ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnGuardar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 235, 18));

        jTextNombre.setBackground(new java.awt.Color(112, 145, 255));
        jTextNombre.setForeground(new java.awt.Color(255, 255, 255));
        jTextNombre.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextNombre.setBorder(null);
        jTextNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextNombreKeyTyped(evt);
            }
        });
        jPanel1.add(jTextNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 235, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 76, -1, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Apellido Paterno");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jSeparator4.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 235, 18));

        jSeparator5.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 235, 18));

        txtApellidoMa.setBackground(new java.awt.Color(112, 145, 255));
        txtApellidoMa.setForeground(new java.awt.Color(255, 255, 255));
        txtApellidoMa.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtApellidoMa.setBorder(null);
        txtApellidoMa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoMaKeyTyped(evt);
            }
        });
        jPanel1.add(txtApellidoMa, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 235, -1));

        txtApellidoPa.setBackground(new java.awt.Color(112, 145, 255));
        txtApellidoPa.setForeground(new java.awt.Color(255, 255, 255));
        txtApellidoPa.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtApellidoPa.setBorder(null);
        txtApellidoPa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoPaKeyTyped(evt);
            }
        });
        jPanel1.add(txtApellidoPa, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 235, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Correo Electronico");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        txtCorreo.setBackground(new java.awt.Color(112, 145, 255));
        txtCorreo.setForeground(new java.awt.Color(255, 255, 255));
        txtCorreo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtCorreo.setBorder(null);
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        jPanel1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 235, -1));

        jSeparator6.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 235, 18));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnGuardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGuardar1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        FormLogin login = new FormLogin();
        login.setVisible(true);
    }//GEN-LAST:event_jbtnGuardar1ActionPerformed

    private void jbtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGuardarActionPerformed
        // TODO add your handling code here:
        // consultas con = new consultas();
        //con.guardarUsuario(jTextNombre.getText(), jTextClave.getText());

        if (contieneDominio(txtCorreo.getText())) {
            DAOUsers dao = new DAOUsersImpl();
            String nombre = jTextNombre.getText(), apePa = txtApellidoPa.getText(), apeMa = txtApellidoMa.getText(), contra = jTextClave.getText(), correo = txtCorreo.getText();
            if (nombre.isEmpty() || apePa.isEmpty() || apeMa.isEmpty() || contra.isEmpty() || correo.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Debe llenar todos los campos. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
            //buscar si existe algun usuario como este
            codigo = new Random().ints(6, 0, 10)
                    .mapToObj(String::valueOf)
                    .reduce("", String::concat);

            email = correo;
            subject = nombre + " " + apePa + " " + " " + apeMa;
            message = "ESTE ES EL CODIGO PARA CREAR TU USUARIO: \n " + codigo;
            try {
                sendEmail();
                // Mostrar un cuadro de diálogo para que el usuario ingrese un código
            } catch (IOException ex) {
                Logger.getLogger(UpUsers.class.getName()).log(Level.SEVERE, null, ex);
            }

            String inputCode = JOptionPane.showInputDialog(null, "Ingrese el código:");

            // Verificar que se haya ingresado un código
            if (inputCode != null && !inputCode.trim().isEmpty()) {
                // Comparar el código ingresado con el código predefinido
                boolean confirmacion = false;
                for (int i = 0; i < 2; i++) {
                    if (!inputCode.equals(codigo)) {
                        JOptionPane.showMessageDialog(null, "Código incorrecto. Por favor, verifique el código.", "Error", JOptionPane.ERROR_MESSAGE);
                        inputCode = JOptionPane.showInputDialog(null, "Ingrese el código:");

                    } else {
                        confirmacion = true;
                        break;
                    }
                }
                if(confirmacion){
                    JOptionPane.showMessageDialog(null, "Código correcto.");
                    com.mycompany.models.Users user =  new com.mycompany.models.Users();
                    user.setName(nombre);
                    user.setLast_name_p(apePa);
                    user.setLast_name_m(apeMa);
                    user.setDomicilio(".");
                    user.setTel(correo);
                    user.setPassword(contra);
                    user.setRole("work");
                    
                    try {
                        

                        
                            dao.registrar(user);
                        
                        String successMsg =  "registrado";

                        javax.swing.JOptionPane.showMessageDialog(this, "Usuario " + successMsg + " exitosamente.\n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                        
                        
                            
                        
                    } catch (Exception e) {
                        String errorMsg = "registrar";
                        javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un error al " + errorMsg + " el usuario. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
                        System.out.println(e.getMessage());
                    }
                }
            }else {
                    // Mostrar un mensaje de error si los códigos no coinciden
                    JOptionPane.showMessageDialog(null, "Código incorrecto. Por favor, verifique el código.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                // Mostrar un mensaje de error si no se ingresó ningún código
                JOptionPane.showMessageDialog(null, "No se ingresó ningún código. Por favor, inténtelo de nuevo.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            
            
        
    }//GEN-LAST:event_jbtnGuardarActionPerformed

    private void jTextClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextClaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextClaveActionPerformed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void jTextNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextNombreKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            evt.consume();  // Ignorar la entrada de caracteres no deseados
        }


    }//GEN-LAST:event_jTextNombreKeyTyped

    private void txtApellidoPaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoPaKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            evt.consume();  // Ignorar la entrada de caracteres no deseados
        }
    }//GEN-LAST:event_txtApellidoPaKeyTyped

    private void txtApellidoMaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoMaKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            evt.consume();  // Ignorar la entrada de caracteres no deseados
        }
    }//GEN-LAST:event_txtApellidoMaKeyTyped

    private void jTextClaveKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextClaveKeyTyped
        // TODO add your handling code here:

        if (jTextClave.getText().length() == 8)
            evt.consume();
        
        
    }//GEN-LAST:event_jTextClaveKeyTyped

    /**
     * @param correo
     * @return
     */
    public static boolean contieneDominio(String correo) {

        if (!(correo.contains("@gmail.com") || correo.contains("@outlook.com") || correo.contains("@itoaxaca.edu.mx"))) {
            JOptionPane.showMessageDialog(null, "tu correo no contiene algun dominio conocido \n prueba de nueva cuenta");
        }
        return correo.contains("@gmail.com") || correo.contains("@outlook.com") || correo.contains("@itoaxaca.edu.mx");
    }

    public void sendEmail() throws IOException {
        // Configuración de las propiedades para la conexión con el servidor SMTP
        Properties props = new Properties();
        props.put("mail.smtp.host", "smtp.gmail.com"); // Cambia "smtp.example.com" por tu servidor SMTP
        props.put("mail.smtp.port", "587"); // Puerto SMTP
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.starttls.enable", "true");

        // Credenciales de autenticación
        String username = "bibliotecatrinity0@gmail.com"; // Cambia por tu dirección de correo electrónico
        String password = "srus nnqo tjng hvkf"; // Cambia por tu contraseña

        // Creación de la sesión
        Session session = Session.getInstance(props,
                new javax.mail.Authenticator() {
            protected javax.mail.PasswordAuthentication getPasswordAuthentication() {
                return new javax.mail.PasswordAuthentication(username, password);
            }
        });

        try {
            // Creación del mensaje
            MimeMessage emailMessage = new MimeMessage(session);
            emailMessage.setFrom(new InternetAddress(username));
            emailMessage.setRecipients(Message.RecipientType.TO, InternetAddress.parse(email));
            emailMessage.setSubject(subject);
            String htmlContent = "<h1 style='color: #0047AB;'>Reporte de la Biblioteca Trinity</h1>"
                    + "<p>Amigo/a Trabajador/a " + subject + "</p>"
                    + "<p>Este es el cogido de autentificacion para agregar tu Usuario.</p>"
                    + "<p>" + message + "<p>"
                    + "<p>¡Gracias por unirte a la familia Trinity!</p>"
                    + "<p>Atentamente,<br/>"
                    + "Biblioteca Trinity</p>"
                    + "© 2024 Biblioteca Trinity. Todos los derechos reservados</p>"
                    + "<p><img src='cid:logo' alt='Logo Biblioteca'></p>"
                    + "<hr/>"
                    + "<p style='font-size: 10px; color: #666;'>© " + Calendar.getInstance().get(Calendar.YEAR) + " Biblioteca Trinity. Todos los derechos reservados.</p>";

            // Adjuntar el archivo PDF al mensaje
            MimeBodyPart messageBodyPart = new MimeBodyPart();
            messageBodyPart.setContent(htmlContent, "text/html; charset=utf-8");

            // Adjuntar la imagen del logo
            MimeBodyPart imagePart = new MimeBodyPart();
            // Cargar la imagen desde el classpath
            InputStream logoStream = getClass().getResourceAsStream("/images/logo.png");
            if (logoStream == null) {
                System.err.println("No se pudo encontrar el archivo logo.png");
                return;
            }
            DataSource fds = new ByteArrayDataSource(logoStream, "image/png");
            imagePart.setDataHandler(new DataHandler(fds));
            imagePart.setHeader("Content-ID", "<logo>");
            imagePart.setDisposition(MimeBodyPart.INLINE);

            // Crear el multipart para el cuerpo del mensaje
            Multipart multipart = new MimeMultipart();
            multipart.addBodyPart(messageBodyPart);
            multipart.addBodyPart(imagePart);
            emailMessage.setContent(multipart);

            // Envío del mensaje
            Transport.send(emailMessage);
            

            JOptionPane.showMessageDialog(null, "Correo electrónico enviado correctamente.");

        } catch (AuthenticationFailedException ex) {
            JOptionPane.showMessageDialog(null, "Error de autenticación al enviar el correo electrónico: " + ex.getMessage());
        } catch (MessagingException ex) {
            JOptionPane.showMessageDialog(null, "Error al enviar el correo electrónico: " + ex.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField jTextClave;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JButton jbtnGuardar;
    private javax.swing.JButton jbtnGuardar1;
    private javax.swing.JTextField txtApellidoMa;
    private javax.swing.JTextField txtApellidoPa;
    private javax.swing.JTextField txtCorreo;
    // End of variables declaration//GEN-END:variables
}
